import { hw } from './hw.js';

const $ = (sel) => document.querySelector(sel);

const els = {
  logInput: $('#log-input'),
  pasteDrop: $('#paste-drop'),
  btnPasteToggle: $('#btn-paste-toggle'),
  btnGenerate: $('#btn-generate'),
  btnDemo: $('#btn-demo'),
  btnMegaDemo: $('#btn-mega-demo'),
  btnClear: $('#btn-clear'),
  cmdChip: $('#cmd-chip'),
  stats: $('#stats'),
  statCommits: $('#stat-commits'),
  statFiles: $('#stat-files'),
  fileFilter: $('#file-filter'),
  btnLaneLayout: $('#btn-lane-layout'),
  stage: $('#stage'),
  fileRail: $('#file-rail'),
  branchRail: $('#branch-rail'),
  fuseBar: $('#hw-fuse-bar'),
  fuseCount: $('#hw-fuse-count'),
  fuseNames: $('#hw-fuse-names'),
  btnFuseClear: $('#btn-fuse-clear'),
  btnFuseCopy: $('#btn-fuse-copy'),
  btnFuseChat: $('#btn-fuse-chat'),
  fileRailInner: $('#file-rail-inner'),
  graphViewport: $('#graph-viewport'),
  graphScroll: $('#graph-scroll'),
  graphEmpty: $('#graph-empty'),
  graphHint: $('#graph-hint'),
  graphSvg: $('#graph-svg'),
  parseError: $('#parse-error'),
  largeWarn: $('#large-data-warn'),
  largeWarnText: $('#large-warn-text'),
  btnLoadMoreCommits: $('#btn-load-more-commits'),
  btnZoomIn: $('#btn-zoom-in'),
  btnZoomOut: $('#btn-zoom-out'),
  btnWhipSound: $('#btn-whip-sound'),
  graphZoom: $('#graph-zoom'),
  zoomLabel: $('#zoom-label'),
  linkPanel: $('#link-panel'),
  linkConstraintText: $('#link-constraint-text'),
  btnCopyLink: $('#btn-copy-link'),
  modalBackdrop: $('#modal-backdrop'),
  modalTitle: $('#modal-title'),
  modalMeta: $('#modal-meta'),
  modalFile: $('#modal-file'),
  modalConstraint: $('#modal-constraint'),
  modalClose: $('#modal-close'),
  tooltip: $('#tooltip'),
  boundaryBar: $('#hw-boundary'),
  boundaryCount: $('#hw-boundary-count'),
  boundaryFiles: $('#hw-boundary-files'),
  boundaryPreview: $('#hw-boundary-preview'),
  btnBoundaryClear: $('#btn-boundary-clear'),
  btnBoundaryCopy: $('#btn-boundary-copy'),
  btnBoundaryChat: $('#btn-boundary-chat'),
};

function isPluginHost() {
  return document.body.classList.contains('hw-plugin');
}

Object.assign(hw, { $, els, isPluginHost });
